### ISSUE TITLE
Add more items.

### ISSUE THREAD

**Issue by BrianZP** [padreon/CreativeLimit#2]
Please add Hoppers, Beacon, Trapped Chest, Anvils, Enchantment Tables, Brewing Stands so that they cannot be accessed in Creative mode.

**Comment by padreon** [comment]
ok

**Comment by BrianZP** [comment]
Geez. Thanks a lot.

**Comment by BrianZP** [comment]
PS I think you forgot to add Beacons (id 138). Also I forgot to mention Droppers (id 125) and Dispensers (id 23). Thanks once again.

**Comment by BrianZP** [comment]
Also on line 109 and 112 the message sent when gamemode is changed from creative to survival  and or in survival mode is wrong. It should be "You are already in survival mode" and "Your are now in survival mode."

**Comment by padreon** [comment]
ok, thx for your suggestion
