### ISSUE TITLE
Inventory cleared even after plugin was removed

### ISSUE THREAD

**Issue by CrazySniper52** [padreon/CreativeLimit#6]
The plugin is great, no doubt... But my staff are getting aggravated at the fact that their inventory is being cleared after each gamemode switch, So i tried to delete the plugin, I also got a ramshard employee to try to remove/delete it. The plugin was deleted in every way possibe, Incuding in the plugin_data, _**Even after we deleted the plugin, When we switch gamemodes our stuff is still taken away**_  Please try to fix this problem. Thanks.

**Comment by padreon** [comment]
Plugins don't work if they don't exist
